print('====== EXERCICIO 4 ======')
# n = int(input('Escreva algo: '))
# n1 = float(input('Escreva algo: '))
# n2 = str(input('Escreva algo: '))
# n3 = bool(input('Escreva algo: '))

n = (input('Escreva algo: '))
print('O tipo primitivo deste valor é ', type(n))
print('Só tem espaço? ', n.isspace())
print('É somente um número? ', n.isnumeric())
print('É somente uma letra? ', n.isalpha())
print('É alfanumerico? ', n.isalnum())
print('Está em letras maiúsculas? ', n.isupper())
print('Está em letras minúsculas? ', n.islower())
print('Está capitalizado? ', n.istitle())
